version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
    - C:\Datos\PostgreSQL:/var/lib/postgresql/data
    environment:
      DATABASE_HOST: "127.0.0.1"
      POSTGRES_USER: "agromerque"
      POSTGRES_PASSWORD: "agromerque"
      POSTGRES_DB: "agromerque"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - postgres
  
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_PORT: 5432
      DATABASE_HOST: "127.0.0.1"
      POSTGRES_USER: "agromerque"
      POSTGRES_PASSWORD: "agromerque"
      POSTGRES_DB: "agromerque"

    depends_on:
      - postgres  
  
